import { h, tag, WeElement } from 'omi'

import '../index'
import '../../space/index'

@tag('icon-icons')
export default class Icons extends WeElement {
  render() {
    return (
      <h>
        <t-space breakLine>
          <t-icon-activity />
          <t-icon-add-and-subtract />
          <t-icon-add-circle />
          <t-icon-add-rectangle />
          <t-icon-add />
          <t-icon-address-book />
          <t-icon-adjustment />
          <t-icon-airplay-wave />
          <t-icon-alarm-add />
          <t-icon-alarm-off />
          <t-icon-alarm />
          <t-icon-align-top />
          <t-icon-align-vertical />
          <t-icon-alpha />
          <t-icon-analytics />
          <t-icon-anchor />
          <t-icon-angry />
          <t-icon-animation-1 />
          <t-icon-animation />
          <t-icon-anticlockwise />
          <t-icon-api />
          <t-icon-app />
          <t-icon-apple />
          <t-icon-application />
          <t-icon-architecture-hui-style />
          <t-icon-archway-1 />
          <t-icon-archway />
          <t-icon-arrow-down-circle />
          <t-icon-arrow-down-rectangle />
          <t-icon-arrow-down />
          <t-icon-arrow-left-circle />
          <t-icon-arrow-left-down-circle />
          <t-icon-arrow-left-down />
          <t-icon-arrow-left-right-1 />
          <t-icon-arrow-left-right-2 />
          <t-icon-arrow-left-right-3 />
          <t-icon-arrow-left-right-circle />
          <t-icon-arrow-left-up-circle />
          <t-icon-arrow-left-up />
          <t-icon-arrow-left />
          <t-icon-arrow-right-circle />
          <t-icon-arrow-right-down-circle />
          <t-icon-arrow-right-down />
          <t-icon-arrow-right-up-circle />
          <t-icon-arrow-right-up />
          <t-icon-arrow-right />
          <t-icon-arrow-triangle-down-filled />
          <t-icon-arrow-triangle-down />
          <t-icon-arrow-triangle-up-filled />
          <t-icon-arrow-triangle-up />
          <t-icon-arrow-up-circle />
          <t-icon-arrow-up-down-1 />
          <t-icon-arrow-up-down-2 />
          <t-icon-arrow-up-down-3 />
          <t-icon-arrow-up-down-circle />
          <t-icon-arrow-up />
          <t-icon-artboard />
          <t-icon-article />
          <t-icon-assignment-checked />
          <t-icon-assignment-code />
          <t-icon-assignment-error />
          <t-icon-assignment-user />
          <t-icon-assignment />
          <t-icon-attach />
          <t-icon-attic-1 />
          <t-icon-attic />
          <t-icon-audio />
          <t-icon-awkward />
          <t-icon-backtop-rectangle />
          <t-icon-backtop />
          <t-icon-backup />
          <t-icon-backward />
          <t-icon-bad-laugh />
          <t-icon-bamboo-shoot />
          <t-icon-banana />
          <t-icon-barbecue />
          <t-icon-barcode-1 />
          <t-icon-barcode />
          <t-icon-base-station />
          <t-icon-battery-add />
          <t-icon-battery-charging />
          <t-icon-battery-low />
          <t-icon-battery />
          <t-icon-bean />
          <t-icon-beer />
          <t-icon-beta />
          <t-icon-bifurcate />
          <t-icon-bill />
          <t-icon-blockchain />
          <t-icon-bluetooth />
          <t-icon-bone />
          <t-icon-book-open />
          <t-icon-book />
          <t-icon-bookmark-add />
          <t-icon-bookmark-checked />
          <t-icon-bookmark-double />
          <t-icon-bookmark-minus />
          <t-icon-bookmark />
          <t-icon-braces />
          <t-icon-brackets />
          <t-icon-bread />
          <t-icon-bridge-1 />
          <t-icon-bridge-2 />
          <t-icon-bridge-3 />
          <t-icon-bridge-4 />
          <t-icon-bridge-5 />
          <t-icon-bridge-6 />
          <t-icon-bridge />
          <t-icon-brightness-1 />
          <t-icon-brightness />
          <t-icon-broccoli />
          <t-icon-browse-gallery />
          <t-icon-browse-off />
          <t-icon-browse />
          <t-icon-brush />
          <t-icon-bug-report />
          <t-icon-bug />
          <t-icon-building-1 />
          <t-icon-building-2 />
          <t-icon-building-3 />
          <t-icon-building-4 />
          <t-icon-building-5 />
          <t-icon-building />
          <t-icon-bulletpoint />
          <t-icon-button />
          <t-icon-cabbage />
          <t-icon-cake />
          <t-icon-calculation-1 />
          <t-icon-calculation />
          <t-icon-calculator-1 />
          <t-icon-calculator />
          <t-icon-calendar-1 />
          <t-icon-calendar-2 />
          <t-icon-calendar-edit />
          <t-icon-calendar-event />
          <t-icon-calendar />
          <t-icon-call-1 />
          <t-icon-call-cancel />
          <t-icon-call-forwarded />
          <t-icon-call-incoming />
          <t-icon-call-off />
          <t-icon-call />
          <t-icon-calm-1 />
          <t-icon-calm />
          <t-icon-camera-1 />
          <t-icon-camera-2 />
          <t-icon-camera-off />
          <t-icon-camera />
          <t-icon-candy />
          <t-icon-card />
          <t-icon-cardmembership />
          <t-icon-caret-down-small />
          <t-icon-caret-down />
          <t-icon-caret-left-small />
          <t-icon-caret-left />
          <t-icon-caret-right-small />
          <t-icon-caret-right />
          <t-icon-caret-up-small />
          <t-icon-caret-up />
          <t-icon-cart-add />
          <t-icon-cart />
          <t-icon-cast />
          <t-icon-castle-1 />
          <t-icon-castle-2 />
          <t-icon-castle-3 />
          <t-icon-castle-4 />
          <t-icon-castle-5 />
          <t-icon-castle-6 />
          <t-icon-castle-7 />
          <t-icon-castle />
          <t-icon-cat />
          <t-icon-catalog />
          <t-icon-cd />
          <t-icon-celsius />
          <t-icon-center-focus-strong />
          <t-icon-centimeter />
          <t-icon-certificate-1 />
          <t-icon-certificate />
          <t-icon-chart-3d />
          <t-icon-chart-add />
          <t-icon-chart-analytics />
          <t-icon-chart-area-multi />
          <t-icon-chart-area />
          <t-icon-chart-bar />
          <t-icon-chart-bubble />
          <t-icon-chart-colum />
          <t-icon-chart-combo />
          <t-icon-chart-line-data-1 />
          <t-icon-chart-line-data />
          <t-icon-chart-line-multi />
          <t-icon-chart-line />
          <t-icon-chart-maximum />
          <t-icon-chart-median />
          <t-icon-chart-minimum />
          <t-icon-chart-pie />
          <t-icon-chart-radar />
          <t-icon-chart-radial />
          <t-icon-chart-ring-1 />
          <t-icon-chart-ring />
          <t-icon-chart-scatter />
          <t-icon-chart-stacked />
          <t-icon-chart />
          <t-icon-chat-add />
          <t-icon-chat-bubble-1 />
          <t-icon-chat-bubble-add />
          <t-icon-chat-bubble-error />
          <t-icon-chat-bubble-help />
          <t-icon-chat-bubble-history />
          <t-icon-chat-bubble-locked />
          <t-icon-chat-bubble-smile />
          <t-icon-chat-bubble />
          <t-icon-chat-checked />
          <t-icon-chat-clear />
          <t-icon-chat-double />
          <t-icon-chat-error />
          <t-icon-chat-heart />
          <t-icon-chat-message />
          <t-icon-chat-off />
          <t-icon-chat-poll />
          <t-icon-chat-setting />
          <t-icon-chat />
          <t-icon-check-circle-filled />
          <t-icon-check-circle />
          <t-icon-check-double />
          <t-icon-check-rectangle-filled />
          <t-icon-check-rectangle />
          <t-icon-check />
          <t-icon-cheese />
          <t-icon-cherry />
          <t-icon-chevron-down-circle />
          <t-icon-chevron-down-double-s />
          <t-icon-chevron-down-double />
          <t-icon-chevron-down-rectangle />
          <t-icon-chevron-down-s />
          <t-icon-chevron-down />
          <t-icon-chevron-left-circle />
          <t-icon-chevron-left-double-s />
          <t-icon-chevron-left-double />
          <t-icon-chevron-left-rectangle />
          <t-icon-chevron-left-s />
          <t-icon-chevron-left />
          <t-icon-chevron-right-circle />
          <t-icon-chevron-right-double-s />
          <t-icon-chevron-right-double />
          <t-icon-chevron-right-rectangle />
          <t-icon-chevron-right-s />
          <t-icon-chevron-right />
          <t-icon-chevron-up-circle />
          <t-icon-chevron-up-double-s />
          <t-icon-chevron-up-double />
          <t-icon-chevron-up-rectangle />
          <t-icon-chevron-up-s />
          <t-icon-chevron-up />
          <t-icon-chicken />
          <t-icon-chili />
          <t-icon-chimney-1 />
          <t-icon-chimney-2 />
          <t-icon-chimney />
          <t-icon-chinese-cabbage />
          <t-icon-church />
          <t-icon-circle />
          <t-icon-city-1 />
          <t-icon-city-10 />
          <t-icon-city-11 />
          <t-icon-city-12 />
          <t-icon-city-13 />
          <t-icon-city-14 />
          <t-icon-city-15 />
          <t-icon-city-2 />
          <t-icon-city-3 />
          <t-icon-city-4 />
          <t-icon-city-5 />
          <t-icon-city-6 />
          <t-icon-city-7 />
          <t-icon-city-8 />
          <t-icon-city-9 />
          <t-icon-city-ancient-1 />
          <t-icon-city-ancient-2 />
          <t-icon-city-ancient />
          <t-icon-city />
          <t-icon-clear-formatting-1 />
          <t-icon-clear-formatting />
          <t-icon-clear />
          <t-icon-close-circle-filled />
          <t-icon-close-circle />
          <t-icon-close-octagon />
          <t-icon-close-rectangle />
          <t-icon-close />
          <t-icon-cloud-download />
          <t-icon-cloud-upload />
          <t-icon-cloud />
          <t-icon-cloudy-day />
          <t-icon-cloudy-night-rain />
          <t-icon-cloudy-night />
          <t-icon-cloudy-rain />
          <t-icon-cloudy-sunny />
          <t-icon-code-1 />
          <t-icon-code-off />
          <t-icon-code />
          <t-icon-cola />
          <t-icon-collage />
          <t-icon-collection />
          <t-icon-color-invert />
          <t-icon-combination />
          <t-icon-command />
          <t-icon-compass-1 />
          <t-icon-compass />
          <t-icon-component-breadcrumb />
          <t-icon-component-checkbox />
          <t-icon-component-divider-horizontal />
          <t-icon-component-divider-vertical />
          <t-icon-component-dropdown />
          <t-icon-component-grid />
          <t-icon-component-input />
          <t-icon-component-layout />
          <t-icon-component-radio />
          <t-icon-component-space />
          <t-icon-component-steps />
          <t-icon-component-switch />
          <t-icon-constraint />
          <t-icon-contrast-1 />
          <t-icon-contrast />
          <t-icon-control-platform />
          <t-icon-cooperate />
          <t-icon-coordinate-system />
          <t-icon-copy />
          <t-icon-copyright />
          <t-icon-corn />
          <t-icon-coupon />
          <t-icon-course />
          <t-icon-cpu />
          <t-icon-crack />
          <t-icon-creditcard-add />
          <t-icon-creditcard-off />
          <t-icon-creditcard />
          <t-icon-crooked-smile />
          <t-icon-cry-and-laugh />
          <t-icon-cry-loudly />
          <t-icon-css3 />
          <t-icon-cucumber />
          <t-icon-currency-exchange />
          <t-icon-cursor />
          <t-icon-curtain />
          <t-icon-curve />
          <t-icon-cut-1 />
          <t-icon-cut />
          <t-icon-dam-1 />
          <t-icon-dam-2 />
          <t-icon-dam-3 />
          <t-icon-dam-4 />
          <t-icon-dam-5 />
          <t-icon-dam-6 />
          <t-icon-dam-7 />
          <t-icon-dam />
          <t-icon-dart-board />
          <t-icon-dashboard-1 />
          <t-icon-dashboard />
          <t-icon-data-base />
          <t-icon-data-checked />
          <t-icon-data-display />
          <t-icon-data-error />
          <t-icon-data-search />
          <t-icon-data />
          <t-icon-delete-1 />
          <t-icon-delete-time />
          <t-icon-delete />
          <t-icon-delta />
          <t-icon-depressed />
          <t-icon-desktop-1 />
          <t-icon-desktop />
          <t-icon-despise />
          <t-icon-device />
          <t-icon-discount-filled />
          <t-icon-discount />
          <t-icon-dissatisfaction />
          <t-icon-divide />
          <t-icon-dividers-1 />
          <t-icon-dividers />
          <t-icon-doge />
          <t-icon-double-storey />
          <t-icon-download-1 />
          <t-icon-download />
          <t-icon-downscale />
          <t-icon-drag-drop />
          <t-icon-drag-move />
          <t-icon-drink />
          <t-icon-drumstick />
          <t-icon-dv />
          <t-icon-dvd />
          <t-icon-earphone />
          <t-icon-earth />
          <t-icon-edit-1 />
          <t-icon-edit-2 />
          <t-icon-edit-off />
          <t-icon-edit />
          <t-icon-education />
          <t-icon-eggplant />
          <t-icon-ellipsis />
          <t-icon-emo-emotional />
          <t-icon-enter />
          <t-icon-equal />
          <t-icon-error-circle-filled />
          <t-icon-error-circle />
          <t-icon-error-triangle />
          <t-icon-error />
          <t-icon-excited-1 />
          <t-icon-excited />
          <t-icon-expand-horizontal />
          <t-icon-expand-vertical />
          <t-icon-explore-off />
          <t-icon-explore />
          <t-icon-exposure />
          <t-icon-extension-off />
          <t-icon-extension />
          <t-icon-face-retouching />
          <t-icon-fact-check />
          <t-icon-fahrenheit-scale />
          <t-icon-feel-at-ease />
          <t-icon-ferocious />
          <t-icon-ferris-wheel />
          <t-icon-file-1 />
          <t-icon-file-add-1 />
          <t-icon-file-add />
          <t-icon-file-attachment />
          <t-icon-file-blocked />
          <t-icon-file-code-1 />
          <t-icon-file-code />
          <t-icon-file-copy />
          <t-icon-file-download />
          <t-icon-file-excel />
          <t-icon-file-export />
          <t-icon-file-icon />
          <t-icon-file-image />
          <t-icon-file-import />
          <t-icon-file-locked />
          <t-icon-file-minus />
          <t-icon-file-music />
          <t-icon-file-onenote />
          <t-icon-file-outlook />
          <t-icon-file-paste />
          <t-icon-file-pdf />
          <t-icon-file-powerpoint />
          <t-icon-file-restore />
          <t-icon-file-safety />
          <t-icon-file-search />
          <t-icon-file-setting />
          <t-icon-file-teams />
          <t-icon-file-unknown />
          <t-icon-file-unlocked />
          <t-icon-file-word />
          <t-icon-file-zip />
          <t-icon-file />
          <t-icon-fill-color-1 />
          <t-icon-fill-color />
          <t-icon-film-1 />
          <t-icon-film />
          <t-icon-filter-1 />
          <t-icon-filter-2 />
          <t-icon-filter-3 />
          <t-icon-filter-clear />
          <t-icon-filter-off />
          <t-icon-filter />
          <t-icon-fingerprint-1 />
          <t-icon-fingerprint-2 />
          <t-icon-fingerprint-3 />
          <t-icon-fingerprint />
          <t-icon-fish />
          <t-icon-flag-1 />
          <t-icon-flag-2 />
          <t-icon-flag-3 />
          <t-icon-flag-4 />
          <t-icon-flag />
          <t-icon-flashlight />
          <t-icon-flight-landing />
          <t-icon-flight-takeoff />
          <t-icon-flip-smiling-face />
          <t-icon-flip-to-back />
          <t-icon-flip-to-front />
          <t-icon-focus />
          <t-icon-fog-night />
          <t-icon-fog-sunny />
          <t-icon-fog />
          <t-icon-folder-1 />
          <t-icon-folder-add-1 />
          <t-icon-folder-add />
          <t-icon-folder-blocked />
          <t-icon-folder-details />
          <t-icon-folder-export />
          <t-icon-folder-import />
          <t-icon-folder-locked />
          <t-icon-folder-minus />
          <t-icon-folder-move />
          <t-icon-folder-off />
          <t-icon-folder-open-1 />
          <t-icon-folder-open />
          <t-icon-folder-search />
          <t-icon-folder-setting />
          <t-icon-folder-shared />
          <t-icon-folder-unlocked />
          <t-icon-folder-zip />
          <t-icon-folder />
          <t-icon-forest />
          <t-icon-fork />
          <t-icon-form />
          <t-icon-format-horizontal-align-bottom />
          <t-icon-format-horizontal-align-center />
          <t-icon-format-horizontal-align-top />
          <t-icon-format-vertical-align-center />
          <t-icon-format-vertical-align-left />
          <t-icon-format-vertical-align-right />
          <t-icon-forward />
          <t-icon-frame-1 />
          <t-icon-frame />
          <t-icon-fries />
          <t-icon-fullscreen-1 />
          <t-icon-fullscreen-2 />
          <t-icon-fullscreen-exit-1 />
          <t-icon-fullscreen-exit />
          <t-icon-fullscreen />
          <t-icon-function-curve />
          <t-icon-functions-1 />
          <t-icon-functions />
          <t-icon-gamepad-1 />
          <t-icon-gamepad />
          <t-icon-gamma />
          <t-icon-garlic />
          <t-icon-gender-female />
          <t-icon-gender-male />
          <t-icon-gesture-applause />
          <t-icon-gesture-click />
          <t-icon-gesture-down />
          <t-icon-gesture-expansion />
          <t-icon-gesture-left-slip />
          <t-icon-gesture-left />
          <t-icon-gesture-pray-1 />
          <t-icon-gesture-pray />
          <t-icon-gesture-press />
          <t-icon-gesture-ranslation-1 />
          <t-icon-gesture-ranslation />
          <t-icon-gesture-right-slip />
          <t-icon-gesture-right />
          <t-icon-gesture-slide-up />
          <t-icon-gesture-up-1 />
          <t-icon-gesture-up-2 />
          <t-icon-gesture-up-and-down />
          <t-icon-gesture-up />
          <t-icon-gesture-wipe-down />
          <t-icon-gift />
          <t-icon-giggle />
          <t-icon-git-branch />
          <t-icon-git-commit />
          <t-icon-git-merge />
          <t-icon-git-pull-request />
          <t-icon-git-repository-commits />
          <t-icon-git-repository-private />
          <t-icon-git-repository />
          <t-icon-gps />
          <t-icon-grape />
          <t-icon-greater-than-or-equal />
          <t-icon-greater-than />
          <t-icon-green-onion />
          <t-icon-grid-add />
          <t-icon-grid-view />
          <t-icon-guitar />
          <t-icon-hamburger />
          <t-icon-happy />
          <t-icon-hard-disk-storage />
          <t-icon-hard-drive />
          <t-icon-hashtag />
          <t-icon-hd />
          <t-icon-heart-filled />
          <t-icon-heart />
          <t-icon-help-circle-filled />
          <t-icon-help-circle />
          <t-icon-help-rectangle />
          <t-icon-help />
          <t-icon-highlight-1 />
          <t-icon-highlight />
          <t-icon-history-setting />
          <t-icon-history />
          <t-icon-home />
          <t-icon-hospital-1 />
          <t-icon-hospital />
          <t-icon-hotspot-wave />
          <t-icon-hourglass />
          <t-icon-houses-1 />
          <t-icon-houses-2 />
          <t-icon-houses />
          <t-icon-html5 />
          <t-icon-https />
          <t-icon-ice-cream />
          <t-icon-icon />
          <t-icon-image-1 />
          <t-icon-image-add />
          <t-icon-image-edit />
          <t-icon-image-error />
          <t-icon-image-off />
          <t-icon-image-search />
          <t-icon-image />
          <t-icon-indent-left />
          <t-icon-indent-right />
          <t-icon-indicator />
          <t-icon-info-circle-filled />
          <t-icon-info-circle />
          <t-icon-ink />
          <t-icon-install-desktop />
          <t-icon-install-mobile />
          <t-icon-install />
          <t-icon-institution-checked />
          <t-icon-institution />
          <t-icon-internet />
          <t-icon-ipod />
          <t-icon-joyful />
          <t-icon-jump-off />
          <t-icon-jump />
          <t-icon-keyboard />
          <t-icon-laptop />
          <t-icon-layers />
          <t-icon-layout />
          <t-icon-leaderboard />
          <t-icon-lemon-slice />
          <t-icon-lemon />
          <t-icon-less-than-or-equal />
          <t-icon-less-than />
          <t-icon-letters-a />
          <t-icon-letters-b />
          <t-icon-letters-c />
          <t-icon-letters-d />
          <t-icon-letters-e />
          <t-icon-letters-f />
          <t-icon-letters-g />
          <t-icon-letters-h />
          <t-icon-letters-i />
          <t-icon-letters-j />
          <t-icon-letters-k />
          <t-icon-letters-l />
          <t-icon-letters-m />
          <t-icon-letters-n />
          <t-icon-letters-o />
          <t-icon-letters-p />
          <t-icon-letters-q />
          <t-icon-letters-r />
          <t-icon-letters-s />
          <t-icon-letters-t />
          <t-icon-letters-u />
          <t-icon-letters-v />
          <t-icon-letters-w />
          <t-icon-letters-x />
          <t-icon-letters-y />
          <t-icon-letters-z />
          <t-icon-lightbulb-circle />
          <t-icon-lightbulb />
          <t-icon-lighthouse-1 />
          <t-icon-lighthouse-2 />
          <t-icon-lighthouse />
          <t-icon-lighting-circle />
          <t-icon-line-height />
          <t-icon-link-1 />
          <t-icon-link-unlink />
          <t-icon-link />
          <t-icon-liquor />
          <t-icon-list />
          <t-icon-load />
          <t-icon-loading />
          <t-icon-location-1 />
          <t-icon-location-enlargement />
          <t-icon-location-error />
          <t-icon-location-parking-place />
          <t-icon-location-reduction />
          <t-icon-location-setting />
          <t-icon-location />
          <t-icon-lock-off />
          <t-icon-lock-on />
          <t-icon-lock-time />
          <t-icon-login />
          <t-icon-logo-adobe-illustrate />
          <t-icon-logo-adobe-photoshop-1 />
          <t-icon-logo-adobe-photoshop />
          <t-icon-logo-android />
          <t-icon-logo-apple-filled />
          <t-icon-logo-apple />
          <t-icon-logo-behance />
          <t-icon-logo-chrome-filled />
          <t-icon-logo-chrome />
          <t-icon-logo-cinema4d />
          <t-icon-logo-codepen />
          <t-icon-logo-codesandbox />
          <t-icon-logo-dribbble />
          <t-icon-logo-facebook />
          <t-icon-logo-figma />
          <t-icon-logo-framer />
          <t-icon-logo-github-filled />
          <t-icon-logo-github />
          <t-icon-logo-gitlab />
          <t-icon-logo-ie-filled />
          <t-icon-logo-ie />
          <t-icon-logo-instagram />
          <t-icon-logo-qq />
          <t-icon-logo-twitter />
          <t-icon-logo-wechat-stroke />
          <t-icon-logo-wechat />
          <t-icon-logo-wecom />
          <t-icon-logo-windows-filled />
          <t-icon-logo-windows />
          <t-icon-logo-youtube />
          <t-icon-logout />
          <t-icon-look-around />
          <t-icon-loudspeaker />
          <t-icon-mail />
          <t-icon-map-3d />
          <t-icon-map-add />
          <t-icon-map-aiming />
          <t-icon-map-blocked />
          <t-icon-map-bubble />
          <t-icon-map-cancel />
          <t-icon-map-chat />
          <t-icon-map-checked />
          <t-icon-map-collection />
          <t-icon-map-connection />
          <t-icon-map-distance />
          <t-icon-map-double />
          <t-icon-map-edit />
          <t-icon-map-grid />
          <t-icon-map-information-1 />
          <t-icon-map-information-2 />
          <t-icon-map-information />
          <t-icon-map-location />
          <t-icon-map-locked />
          <t-icon-map-marked />
          <t-icon-map-navigation />
          <t-icon-map-outline />
          <t-icon-map-route-planning />
          <t-icon-map-ruler />
          <t-icon-map-safety />
          <t-icon-map-search-1 />
          <t-icon-map-search />
          <t-icon-map-setting />
          <t-icon-map-unlocked />
          <t-icon-map />
          <t-icon-mark-as-unread />
          <t-icon-markup />
          <t-icon-mathematics />
          <t-icon-measurement-1 />
          <t-icon-measurement-2 />
          <t-icon-measurement />
          <t-icon-meat-pepper />
          <t-icon-media-library />
          <t-icon-member />
          <t-icon-menu-application />
          <t-icon-menu-fold />
          <t-icon-menu-unfold />
          <t-icon-menu />
          <t-icon-merge-cells />
          <t-icon-microphone-1 />
          <t-icon-microphone-2 />
          <t-icon-microphone />
          <t-icon-milk />
          <t-icon-minus-circle-filled />
          <t-icon-minus-circle />
          <t-icon-minus-rectangle-filled />
          <t-icon-minus-rectangle />
          <t-icon-minus />
          <t-icon-mirror />
          <t-icon-mobile-blocked />
          <t-icon-mobile-list />
          <t-icon-mobile-navigation />
          <t-icon-mobile-shortcut />
          <t-icon-mobile-vibrate />
          <t-icon-mobile />
          <t-icon-mode-dark />
          <t-icon-mode-light />
          <t-icon-module />
          <t-icon-money />
          <t-icon-monument />
          <t-icon-moon-fall />
          <t-icon-moon-rising />
          <t-icon-moon />
          <t-icon-more />
          <t-icon-mosque-1 />
          <t-icon-mosque />
          <t-icon-mouse />
          <t-icon-move-1 />
          <t-icon-move />
          <t-icon-movie-clapper />
          <t-icon-multiply />
          <t-icon-museum-1 />
          <t-icon-museum-2 />
          <t-icon-museum />
          <t-icon-mushroom-1 />
          <t-icon-mushroom />
          <t-icon-music-1 />
          <t-icon-music-2 />
          <t-icon-music-rectangle-add />
          <t-icon-music />
          <t-icon-navigation-arrow />
          <t-icon-next />
          <t-icon-no-expression />
          <t-icon-noodle />
          <t-icon-notification-add />
          <t-icon-notification-circle />
          <t-icon-notification-error />
          <t-icon-notification-filled />
          <t-icon-notification />
          <t-icon-numbers-0-1 />
          <t-icon-numbers-0 />
          <t-icon-numbers-1-1 />
          <t-icon-numbers-1 />
          <t-icon-numbers-2-1 />
          <t-icon-numbers-2 />
          <t-icon-numbers-3-1 />
          <t-icon-numbers-3 />
          <t-icon-numbers-4-1 />
          <t-icon-numbers-4 />
          <t-icon-numbers-5-1 />
          <t-icon-numbers-5 />
          <t-icon-numbers-6-1 />
          <t-icon-numbers-6 />
          <t-icon-numbers-7-1 />
          <t-icon-numbers-7 />
          <t-icon-numbers-8-1 />
          <t-icon-numbers-8 />
          <t-icon-numbers-9-1 />
          <t-icon-numbers-9 />
          <t-icon-nut />
          <t-icon-object-storage />
          <t-icon-open-mouth />
          <t-icon-opera />
          <t-icon-order-adjustment-column />
          <t-icon-order-ascending />
          <t-icon-order-descending />
          <t-icon-outbox />
          <t-icon-page-first />
          <t-icon-page-head />
          <t-icon-page-last />
          <t-icon-palace-1 />
          <t-icon-palace-2 />
          <t-icon-palace-3 />
          <t-icon-palace-4 />
          <t-icon-palace />
          <t-icon-palette-1 />
          <t-icon-palette />
          <t-icon-panorama-horizontal />
          <t-icon-panorama-vertical />
          <t-icon-pantone />
          <t-icon-parabola />
          <t-icon-parentheses />
          <t-icon-paste />
          <t-icon-patio />
          <t-icon-pause-circle-filled />
          <t-icon-pause-circle-stroke />
          <t-icon-pause-circle />
          <t-icon-pause />
          <t-icon-pea />
          <t-icon-peach />
          <t-icon-pear />
          <t-icon-pearl-of-the-orient />
          <t-icon-pen-ball />
          <t-icon-pen-brush />
          <t-icon-pen-mark />
          <t-icon-pen-quill />
          <t-icon-pen />
          <t-icon-pending />
          <t-icon-percent />
          <t-icon-personal-information />
          <t-icon-phone-locked />
          <t-icon-phone-search />
          <t-icon-pi />
          <t-icon-piano />
          <t-icon-pin-filled />
          <t-icon-pin />
          <t-icon-play-circle-filled />
          <t-icon-play-circle-stroke-add />
          <t-icon-play-circle-stroke />
          <t-icon-play-circle />
          <t-icon-play-demo />
          <t-icon-play-rectangle />
          <t-icon-play />
          <t-icon-plus />
          <t-icon-popsicle />
          <t-icon-portrait />
          <t-icon-pout />
          <t-icon-poweroff />
          <t-icon-precise-monitor />
          <t-icon-previous />
          <t-icon-print />
          <t-icon-pumpkin />
          <t-icon-pyramid-maya />
          <t-icon-pyramid />
          <t-icon-qrcode />
          <t-icon-quadratic />
          <t-icon-questionnaire />
          <t-icon-queue />
          <t-icon-radar />
          <t-icon-radio-1 />
          <t-icon-radio-2 />
          <t-icon-radish />
          <t-icon-rain-heavy />
          <t-icon-rain-light />
          <t-icon-rain-medium />
          <t-icon-rainbow />
          <t-icon-rectangle />
          <t-icon-refresh />
          <t-icon-relation />
          <t-icon-relativity />
          <t-icon-remote-wave />
          <t-icon-remove />
          <t-icon-replay />
          <t-icon-rice-ball />
          <t-icon-rice />
          <t-icon-roast />
          <t-icon-rocket />
          <t-icon-rollback />
          <t-icon-rollfront />
          <t-icon-root-list />
          <t-icon-rotate-locked />
          <t-icon-rotate />
          <t-icon-rotation />
          <t-icon-round />
          <t-icon-router-wave />
          <t-icon-rss />
          <t-icon-ruler />
          <t-icon-sailing-hotel />
          <t-icon-sandwich />
          <t-icon-saturation />
          <t-icon-sausage />
          <t-icon-save />
          <t-icon-saving-pot />
          <t-icon-scan />
          <t-icon-screen-4k />
          <t-icon-screencast />
          <t-icon-screenshot />
          <t-icon-scroll-bar />
          <t-icon-sd-card-1 />
          <t-icon-sd-card />
          <t-icon-search-error />
          <t-icon-search />
          <t-icon-secured />
          <t-icon-send-cancel />
          <t-icon-send />
          <t-icon-sensors-1 />
          <t-icon-sensors-2 />
          <t-icon-sensors-off />
          <t-icon-sensors />
          <t-icon-serenity />
          <t-icon-server />
          <t-icon-service />
          <t-icon-setting-1 />
          <t-icon-setting />
          <t-icon-share-1 />
          <t-icon-share />
          <t-icon-sharpness />
          <t-icon-shield-error />
          <t-icon-shimen />
          <t-icon-shop-1 />
          <t-icon-shop-2 />
          <t-icon-shop-3 />
          <t-icon-shop-4 />
          <t-icon-shop-5 />
          <t-icon-shop />
          <t-icon-shrimp />
          <t-icon-shrink-horizontal />
          <t-icon-shrink-vertical />
          <t-icon-shutter />
          <t-icon-shutup />
          <t-icon-sim-card-1 />
          <t-icon-sim-card-2 />
          <t-icon-sim-card />
          <t-icon-sinister-smile />
          <t-icon-sip />
          <t-icon-slash />
          <t-icon-sleep />
          <t-icon-slice />
          <t-icon-slideshow />
          <t-icon-smile />
          <t-icon-sneer />
          <t-icon-snowflake />
          <t-icon-sonic />
          <t-icon-sound-down />
          <t-icon-sound-high />
          <t-icon-sound-low />
          <t-icon-sound-mute-1 />
          <t-icon-sound-mute />
          <t-icon-sound-up />
          <t-icon-sound />
          <t-icon-space />
          <t-icon-speechless-1 />
          <t-icon-star-filled />
          <t-icon-star />
          <t-icon-statue-of-jesus />
          <t-icon-sticky-note />
          <t-icon-stop-circle-filled />
          <t-icon-stop-circle-stroke />
          <t-icon-stop-circle />
          <t-icon-stop />
          <t-icon-store />
          <t-icon-street-road-1 />
          <t-icon-street-road />
          <t-icon-subtitle />
          <t-icon-subway-line />
          <t-icon-sum />
          <t-icon-sun-fall />
          <t-icon-sun-rising />
          <t-icon-sunny />
          <t-icon-support />
          <t-icon-surprised-1 />
          <t-icon-surprised />
          <t-icon-swap-left />
          <t-icon-swap-right />
          <t-icon-swap />
          <t-icon-swear-1 />
          <t-icon-swear-2 />
          <t-icon-system-2 />
          <t-icon-system-3 />
          <t-icon-system-application />
          <t-icon-system-blocked />
          <t-icon-system-code />
          <t-icon-system-components />
          <t-icon-system-coordinate />
          <t-icon-system-device />
          <t-icon-system-interface />
          <t-icon-system-location />
          <t-icon-system-locked />
          <t-icon-system-log />
          <t-icon-system-marked />
          <t-icon-system-messages />
          <t-icon-system-regulation />
          <t-icon-system-search />
          <t-icon-system-setting />
          <t-icon-system-storage />
          <t-icon-system-sum />
          <t-icon-system-unlocked />
          <t-icon-tab />
          <t-icon-table-1 />
          <t-icon-table-2 />
          <t-icon-table-add />
          <t-icon-table-split />
          <t-icon-table />
          <t-icon-tag />
          <t-icon-tangerinr />
          <t-icon-tape />
          <t-icon-task-1 />
          <t-icon-task-add-1 />
          <t-icon-task-add />
          <t-icon-task-checked />
          <t-icon-task-error />
          <t-icon-task-location />
          <t-icon-task-marked />
          <t-icon-task-setting />
          <t-icon-task-visible />
          <t-icon-task />
          <t-icon-tea />
          <t-icon-teahouse />
          <t-icon-template />
          <t-icon-temple />
          <t-icon-terminal-rectangle-1 />
          <t-icon-terminal-rectangle />
          <t-icon-terminal-window />
          <t-icon-terminal />
          <t-icon-textbox />
          <t-icon-textformat-bold />
          <t-icon-textformat-color />
          <t-icon-textformat-italic />
          <t-icon-textformat-strikethrough />
          <t-icon-textformat-underline />
          <t-icon-textformat-wrap />
          <t-icon-theaters />
          <t-icon-thumb-down-1 />
          <t-icon-thumb-down-2 />
          <t-icon-thumb-down />
          <t-icon-thumb-up-1 />
          <t-icon-thumb-up-2 />
          <t-icon-thumb-up />
          <t-icon-thunder />
          <t-icon-thunderstorm-night />
          <t-icon-thunderstorm-sunny />
          <t-icon-thunderstorm />
          <t-icon-ticket />
          <t-icon-time-filled />
          <t-icon-time />
          <t-icon-tips-double />
          <t-icon-tips />
          <t-icon-tomato />
          <t-icon-tools-circle />
          <t-icon-tools />
          <t-icon-tornado />
          <t-icon-tower-1 />
          <t-icon-tower-2 />
          <t-icon-tower-3 />
          <t-icon-tower-clock />
          <t-icon-tower />
          <t-icon-town />
          <t-icon-traffic-events />
          <t-icon-traffic />
          <t-icon-transform-1 />
          <t-icon-transform-2 />
          <t-icon-transform-3 />
          <t-icon-transform />
          <t-icon-translate-1 />
          <t-icon-translate />
          <t-icon-tree-list />
          <t-icon-tree-round-dot-vertical />
          <t-icon-tree-round-dot />
          <t-icon-tree-square-dot-vertical />
          <t-icon-tree-square-dot />
          <t-icon-trending-down />
          <t-icon-trending-up />
          <t-icon-tv-1 />
          <t-icon-tv-2 />
          <t-icon-tv />
          <t-icon-typography />
          <t-icon-uncomfortable-1 />
          <t-icon-uncomfortable-2 />
          <t-icon-uncomfortable />
          <t-icon-undertake-delivery />
          <t-icon-undertake-environment-protection />
          <t-icon-undertake-hold-up />
          <t-icon-undertake-transaction />
          <t-icon-undertake />
          <t-icon-unfold-less />
          <t-icon-unfold-more />
          <t-icon-unhappy-1 />
          <t-icon-unhappy />
          <t-icon-uninstall />
          <t-icon-upload-1 />
          <t-icon-upload />
          <t-icon-upscale />
          <t-icon-usb />
          <t-icon-user-1 />
          <t-icon-user-add />
          <t-icon-user-arrow-down />
          <t-icon-user-arrow-left />
          <t-icon-user-arrow-right />
          <t-icon-user-arrow-up />
          <t-icon-user-avatar />
          <t-icon-user-blocked />
          <t-icon-user-business />
          <t-icon-user-checked-1 />
          <t-icon-user-checked />
          <t-icon-user-circle />
          <t-icon-user-clear />
          <t-icon-user-error-1 />
          <t-icon-user-invisible />
          <t-icon-user-list />
          <t-icon-user-locked />
          <t-icon-user-marked />
          <t-icon-user-password />
          <t-icon-user-safety />
          <t-icon-user-search />
          <t-icon-user-setting />
          <t-icon-user-talk-1 />
          <t-icon-user-talk-off-1 />
          <t-icon-user-talk />
          <t-icon-user-time />
          <t-icon-user-transmit />
          <t-icon-user-unknown />
          <t-icon-user-unlocked />
          <t-icon-user-vip />
          <t-icon-user-visible />
          <t-icon-user />
          <t-icon-usergroup-add />
          <t-icon-usergroup-clear />
          <t-icon-usergroup />
          <t-icon-vehicle />
          <t-icon-verified />
          <t-icon-verify />
          <t-icon-video-camera-1 />
          <t-icon-video-camera-2 />
          <t-icon-video-camera-dollar />
          <t-icon-video-camera-minus />
          <t-icon-video-camera-music />
          <t-icon-video-camera-off />
          <t-icon-video-camera />
          <t-icon-video-library />
          <t-icon-video />
          <t-icon-view-agenda />
          <t-icon-view-column />
          <t-icon-view-in-ar />
          <t-icon-view-list />
          <t-icon-view-module />
          <t-icon-visual-recognition />
          <t-icon-wallet />
          <t-icon-watch />
          <t-icon-watermelon />
          <t-icon-wave-left />
          <t-icon-wave-right />
          <t-icon-wealth-1 />
          <t-icon-wealth />
          <t-icon-widget />
          <t-icon-wifi-1 />
          <t-icon-wifi-off-1 />
          <t-icon-wifi-off />
          <t-icon-wifi />
          <t-icon-window-1 />
          <t-icon-window />
          <t-icon-windy-rain />
          <t-icon-windy />
          <t-icon-wink />
          <t-icon-work-history />
          <t-icon-work-off />
          <t-icon-work />
          <t-icon-wry-smile />
          <t-icon-zoom-in />
          <t-icon-zoom-out />
        </t-space>
      </h>
    )
  }
}
